# frozen_string_literal: true
# This file is auto-generated by the TNG/nono release pipeline.
# Do not edit by hand; changes will be overwritten on the next release.
class Nono < Formula
  desc "Capability-based sandbox for running untrusted commands"
  homepage "https://github.com/TNG/nono"
  version "0.43.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.43.1/nono-v0.43.1-aarch64-apple-darwin.tar.gz"
      sha256 "f71adb302fcdc388beae98a22936a1c22203b2e725a3837ef0d54aaf3fc4aff2"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.43.1/nono-v0.43.1-x86_64-apple-darwin.tar.gz"
      sha256 "8918e1daa3340e6d6d368f8f0ef02856310e6508b8a417fcd3a6e454e1a7edd0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.43.1/nono-v0.43.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "09cc6ca468cf4c4957f7fefe517c171c8ae2031ea3e4fd51b20aa9b906c307e9"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.43.1/nono-v0.43.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "63112af447b11486939b9bea5cab18bbad98ae96b239bb898278718bf47ef2bb"
    end
  end

  def install
    bin.install "nono"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nono --version")
  end
end
