# frozen_string_literal: true
# This file is auto-generated by the TNG/nono release pipeline.
# Do not edit by hand; changes will be overwritten on the next release.
class Nono < Formula
  desc "Capability-based sandbox for running untrusted commands"
  homepage "https://github.com/TNG/nono"
  version "0.44.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.44.1/nono-v0.44.1-aarch64-apple-darwin.tar.gz"
      sha256 "6e621f31bcf29917b546a1fedf08b7699fbdbdfcb2ab7473d3c92d9c9b4d27c5"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.44.1/nono-v0.44.1-x86_64-apple-darwin.tar.gz"
      sha256 "dc40d012d67d081492e93ea7e1307124d7d5bfaf33f7bca1eaac81c6164aa27d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.44.1/nono-v0.44.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "90949a85b6472ad2dc9691d5efbf186e913dc96d669426d17991a76fc2ab8b20"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.44.1/nono-v0.44.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7d5e854c1f836e832d1df8e210793825cf4481660c48b54c1dd5260df61d9f53"
    end
  end

  def install
    bin.install "nono"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nono --version")
  end
end
