# frozen_string_literal: true
# This file is auto-generated by the TNG/nono release pipeline.
# Do not edit by hand; changes will be overwritten on the next release.
class NonoTng < Formula
  desc "Capability-based sandbox for running untrusted commands (TNG fork)"
  homepage "https://github.com/TNG/nono"
  version "0.44.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.44.3/nono-tng-v0.44.3-aarch64-apple-darwin.tar.gz"
      sha256 "0c0221f890c9546bae17e0e35755e24204423371b14fcd559eca0e6397f9ba8e"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.44.3/nono-tng-v0.44.3-x86_64-apple-darwin.tar.gz"
      sha256 "17f67a04694223686a475e60132947391418ffc1f256f5705be586d2641dfb8d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TNG/nono/releases/download/v0.44.3/nono-tng-v0.44.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "792b153d511d8d87181c09c562fabbcc84dfddf62d6722ddea6805fc3471f10f"
    end
    on_intel do
      url "https://github.com/TNG/nono/releases/download/v0.44.3/nono-tng-v0.44.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5aa5af8af9a608dd48b1c6116686e419ce9535885a4fb643ffaa2822bfd17615"
    end
  end

  def install
    bin.install "nono-tng"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nono-tng --version")
  end
end
