# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OhMyAgenticCoder < Formula
  desc "Sandboxed agent-coding facade with keychain-backed secrets."
  homepage "https://github.com/TNG/oh-my-agentic-coder"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TNG/oh-my-agentic-coder/releases/download/v0.4.5/oh-my-agentic-coder_0.4.5_macOS_x86_64.tar.gz"
      sha256 "a49809fc122c3354b7ab0cf47dbb12957398a2cd6afca527ea214b3c7960a953"

      define_method(:install) do
        bin.install "omac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TNG/oh-my-agentic-coder/releases/download/v0.4.5/oh-my-agentic-coder_0.4.5_macOS_arm64.tar.gz"
      sha256 "52756da5a86b4511a6316b324a53b9688646bd0b8ee603ffb20035edd15b1e06"

      define_method(:install) do
        bin.install "omac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TNG/oh-my-agentic-coder/releases/download/v0.4.5/oh-my-agentic-coder_0.4.5_linux_x86_64.tar.gz"
      sha256 "c787e58f8475ca22d29a9fa6344035583bd0fa5d11e3735bddea6f26fb296612"
      define_method(:install) do
        bin.install "omac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TNG/oh-my-agentic-coder/releases/download/v0.4.5/oh-my-agentic-coder_0.4.5_linux_arm64.tar.gz"
      sha256 "8bbfe913e64bed67676f74bfb50ddd53014b9c4bad1d38408297040972c3c7da"
      define_method(:install) do
        bin.install "omac"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omac --version")
  end
end
